---

stages:
  - test
  - deploy

.build_template: &build_definition
  image: ocaml/opam2:alpine-3.10-ocaml-4.08
  script:
    - sudo apk --no-cache add m4
    - opam pin --no-action ezresto-directory .
    - opam pin --no-action ezresto .
    - opam pin --no-action resto-cohttp-client .
    - opam pin --no-action resto-cohttp .
    - opam pin --no-action resto-cohttp-server .
    - opam pin --no-action resto-directory .
    - opam pin --no-action resto-json .
    - opam pin --no-action resto .
    - opam depext ezresto-directory ezresto resto-cohttp-client \
      resto-cohttp resto-cohttp-server resto-directory resto-json resto
    - opam install --deps-only .
    - dune build
    - opam install odoc
    - dune build @doc
    - mv _build/default/_doc/_html public/
    - dune runtest
    - opam install .


test-fmt:
  stage: test
  image: ocaml/opam2:alpine-3.10-ocaml-4.08
  script:
    - sudo apk --no-cache add m4
    - opam install ocamlformat.0.10
    - ocamlformat --check src/*.ml src/*.mli test/*.ml

pages:
  <<: *build_definition
  stage: deploy
  artifacts:
    paths:
    - public/
  only:
  - master

test:
  <<: *build_definition
  stage: test
  only:
  - branches
  except:
  - master
