---

build-and-test:
  image: ocaml/opam2:alpine-3.10-ocaml-4.08
  script:
    - opam lint .
    - sudo apk --no-cache add m4
    - opam install ocamlformat.0.10
    - ocamlformat --check src/*.ml src/*.mli test/*.ml
    - opam pin --no-action ezresto-directory .
    - opam pin --no-action ezresto .
    - opam pin --no-action resto-cohttp-client .
    - opam pin --no-action resto-cohttp .
    - opam pin --no-action resto-cohttp-server .
    - opam pin --no-action resto-directory .
    - opam pin --no-action resto-json .
    - opam pin --no-action resto .
    - opam depext ezresto-directory ezresto resto-cohttp-client \
      resto-cohttp resto-cohttp-server resto-directory resto-json resto
    - opam install --deps-only .
    - dune build
    - dune runtest
    - opam install .

pages:
  image: ocaml/opam2:alpine-3.10-ocaml-4.08
  artifacts:
    paths:
    - public/
  only:
  - master
  script:
    - sudo apk --no-cache add m4
    - opam pin --no-action ezresto-directory .
    - opam pin --no-action ezresto .
    - opam pin --no-action resto-cohttp-client .
    - opam pin --no-action resto-cohttp .
    - opam pin --no-action resto-cohttp-server .
    - opam pin --no-action resto-directory .
    - opam pin --no-action resto-json .
    - opam pin --no-action resto .
    - opam depext ezresto-directory ezresto resto-cohttp-client \
      resto-cohttp resto-cohttp-server resto-directory resto-json resto
    - opam install --deps-only .
    - opam install odoc
    - dune build @doc
    - mv _build/default/_doc/_html public/
