default:
  interruptible: true
  tags:
  - gcp

stages:
- test

test_protected_variable:
  stage: cababilities
  image: "${GCP_REGISTRY}/nomadic-labs/iac/docker/ci-devops:v1.3.0"
  script:
  - echo $GCP_REGISTRY
  - echo $CI_COMMIT_REF_PROTECTED
