include: 'https://gitlab.com/nomadic-labs/gitlab-ocaml-ci-example/-/raw/main/.gitlab-ci.yml'

.build-matrix:
  parallel:
    matrix:
    - OCAML_COMPILER: "4.08.1"
    - OCAML_COMPILER: "4.09.1"
    - OCAML_COMPILER: "4.10.0"
    - OCAML_COMPILER: "4.11.1"

variables:
  CLEAN_OPAM_CACHE: "false"
  CLEAN_DUNE_CACHE: "false"
  DUNE_BUILD_TARGETS: "@src/all"
  DUNE_TEST_TARGETS: "@fmt @runtest"
  DUNE_DOC_TARGETS: "@doc"
