---
image: alpine:3.16

default:
  interruptible: true

stages:
  - build
  - release

build:
  tags:
    - gcp
  stage: build
  before_script:
    - apk add git make go
    - go install github.com/google/go-jsonnet/cmd/jsonnet@latest
    - go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
    - export PATH="$PATH:$(go env GOPATH)/bin"
    - jb install
  script:
    - make
  artifacts:
    paths:
      - "output/*.json"
    expire_in: 2 weeks
    when: always
  only:
    - master
    - merge_requests
    - tags

release:
  tags:
    - gcp
  stage: release
  dependencies: [build]
  before_script:
    - apk add curl
  script:
    - ./.gitlab/create_gitlab_package.sh
  only:
    - tags
