[package]
name = "bin_dsn_node"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
hyper = { version = "1.3.1" , features = ["full"]}
tokio-util = { version = "0.7.10", features = ["compat"] }
serde_json = "1.0.116"
tokio-stream = "0.1.15"
hyper-util = {version = "0.1.3", features = ["tokio"] }
http-body-util = "0.1.1"
futures = "0.3.30"
serde = "1.0.198"
anyhow = "1.0.82"
serde_derive = "1.0.198"
url = "2.5.0"
chrono = { version = "0.4.38", features = ["serde"] }
hex = { version = "0.4.3", features = ["serde"] }
tokio-retry = "0.3.0"
thiserror = "1.0.58"
http-body = "1.0.0"
bytes = "1.6.0"
