version: "3"
services:
  octez-node:
    container_name: octez-node
    image: tezos/tezos:latest
    hostname: octez-node
    command: octez-node
    ports:
      - 9732:9732
      - 8732:8732
    volumes:
      - node_data:/var/run/tezos/node
      - client_data:/var/run/tezos/client
    restart: on-failure

  teztale-server:
    container_name: teztale-server
    image: registry.gitlab.com/nomadic-labs/teztale/server:master
    hostname: teztale-server
    ports:
      - 8880:8880
    volumes:
      - ./examples/server-config.json:/etc/teztale/config.json
      - teztale-db:/data
    restart: on-failure

  teztale-archiver:
    container_name: teztale-archiver
    image: registry.gitlab.com/nomadic-labs/teztale/archiver:master
    command: --endpoint http://octez-node:8732 feed http://teztale-server:8880 -u admin -p secret
    restart: on-failure

volumes:
  node_data: {}
  client_data: {}
  teztale-db: {}
