[package]
name = "octez-risc-v-api"
version = "0.0.0"
edition = "2021"

[dependencies.ocaml]
version = "^1.0.0-beta"

[dependencies.risc-v-interpreter]
path = "../interpreter"

[build-dependencies.ocaml-build]
version = "^1.0.0-beta"
