[workspace]
resolver = "2"
members = [
  # Libraries
  "interpreter",
  "pvm",
  "api",
  # Executables
  "sandbox",
]
exclude = ["jstz", "dummy_kernel", "tests"]

[workspace.dependencies]
derive_more = "0.99.17"
enum-tag = "0.3.0"
goblin = "0.7.1"
hex = "0.4.3"
ieee-apsqrt = "0.1.1"
lazy_static = "1.4.0"
num_enum = "0.7.2"
paste = "1.0.14"
proptest = "1.4.0"
rand = "0.8.5"
rustc_apfloat = "0.2.0"
thiserror = "1.0.57"
twiddle = "1.1.0"
vm-fdt = "0.3.0"

[workspace.dependencies.rvemu]
git = "https://github.com/vapourismo/rvemu.git"
branch = "pub-translate"

[workspace.dependencies.strum]
version = "0.26.1"
features = ["derive"]
