[workspace]
resolver = "2"
members = [
  # Libraries
  "kernel_loader",
  "interpreter",
  "pvm",
  # Executables
  "sandbox",
]
exclude = ["jstz", "dummy_kernel", "tests"]

[workspace.dependencies]
softfloat-sys = { git = "https://gitlab.com/trili/softfloat-sys" }

[patch.crates-io]
softfloat-sys = { git = "https://gitlab.com/trili/softfloat-sys" }
