[package]
name = "risc-v-interpreter"
version = "0.0.0"
edition = "2021"

[dependencies]
enum-tag.workspace = true
num_enum.workspace = true
paste.workspace = true
thiserror.workspace = true
twiddle.workspace = true
vm-fdt.workspace = true
rustc_apfloat.workspace = true
ieee-apsqrt.workspace = true
goblin.workspace = true
derive_more.workspace = true
rvemu.workspace = true
strum.workspace = true

[dev-dependencies]
hex.workspace = true
rand.workspace = true
proptest.workspace = true
lazy_static.workspace = true

[dependencies.tezos-smart-rollup-constants]
path = "../../kernel_sdk/constants"
