[package]
name = "octez-risc-v-interpreter"
version = "0.0.0"
edition = "2021"

[dependencies]
derive_more.workspace = true
enum-tag.workspace = true
goblin.workspace = true
ieee-apsqrt.workspace = true
num_enum.workspace = true
paste.workspace = true
rustc_apfloat.workspace = true
rvemu.workspace = true
strum.workspace = true
tezos-smart-rollup-constants.workspace = true
thiserror.workspace = true
twiddle.workspace = true
vm-fdt.workspace = true

[dependencies.ocaml]
workspace = true
optional = true

[build-dependencies]
ocaml-build.workspace = true

[dev-dependencies]
hex.workspace = true
rand.workspace = true
proptest.workspace = true
lazy_static.workspace = true

[features]
default = []
ocaml-api = ["ocaml"]
